### ISSUE TITLE
Line 20 does not work

### ISSUE THREAD

**Issue by jfryer9** [PacktPublishing/Regression-Analysis-with-R#1]
There is a problem with the Confusion Matrix in this code.  When I run it with R 4.1.1, I get this exception:
Error:  `data` and `reference` should be factors with the same levels.

The line:  confusionMatrix(LGModel1Pred, data[ ,"CustomerWillTip"]) appears to expand in the traceback to:
confusionMatrix.default(LGModel1Pred, data[  ,"CustomerWillTip"])

**Comment by CiaburroGiuseppe** [comment]
Dear reader, thank you for purchasing my book
In the new version of the caret library, the need for both values of a confusion matrix to be of the type factor has been implemented. So just edit the line that returns the error as follows:

LGModel1CM <- confusionMatrix(as.factor(LGModel1Pred), as.factor(data[,"CustomerWillTip"]))

Best regards.

**Comment by nithikpackt** [comment]
Thank you @CiaburroGiuseppe for the solution. Closing the issue for now. @jfryer9 , please reopen the issue in case of any further queries.
